version: "3"
services:
  app:
    image: golang:1.21.1
    container_name: go-fiber-note
    ports:
      - "3000:3000"
    command: bash deploy.sh
    volumes:
      - .:/go/src/app
    working_dir: /go/src/app
    env_file:
      - .env
